feat: better module error handling and error propagation (#368)
I noticed that if error occurs in a module (e. g. caused by some syntax error in its (meta)data) it does not propagate the error to the user, but it just doesn't hit anything. In my opinion, it can be very misleading during the debugging process.

Therefore, I've got an idea to change the return type of module `MainFn` to `Result<Box<dyn MessageDyn>, ModuleError>`, which allow to return a string with description of an error which appeared inside a module.

For example if there is missing `,` in cuckoo JSON report we now get:
```
$ ./target/debug/yr scan -x cuckoo=cuckoo.json test.yar test.yar
error:  scanning "test.yar": error un module `cuckoo`: invalid metadata: expected `,` or `}` at line 6 column 5
────────────────────────────────────────────────────────────────────────────────────────────────────────
 0 file(s) scanned in 0.3s. 0 file(s) matched.
```

---------

Co-authored-by: Victor M. Alvarez <vmalvarez@virustotal.com>