fix: remove .js extension from module import path.
After upgrading to NodeJS 24 compilation started to fail with:
src/editor/yara-monaco.ts(8,8): error TS2307: Cannot find module 'vscode-languageserver-protocol/browser.js' or its corresponding type declarations.